<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { createQuestion, deleteQuestion, getQuestions, updateQuestion } from '../api/question'
import { getCourses } from '../api/course'
import { ElMessage, ElMessageBox } from 'element-plus'
const rows=ref([]),courses=ref([]),total=ref(0),visible=ref(false),editing=ref(null)
const query=reactive({page:1,size:10,courseId:null,questionType:'',difficulty:'',knowledgeTag:''})
const form=reactive({courseId:null,questionType:'SINGLE_CHOICE',content:'',options:['','','',''],answer:'',analysis:'',difficulty:'EASY',score:5,knowledgeTag:''})
const choice=computed(()=>['SINGLE_CHOICE','MULTIPLE_CHOICE'].includes(form.questionType))
const types=[['SINGLE_CHOICE','单选'],['MULTIPLE_CHOICE','多选'],['TRUE_FALSE','判断'],['FILL_BLANK','填空'],['SHORT_ANSWER','简答']]
async function load(){const d=await getQuestions(query);rows.value=d.records;total.value=d.total}
function parseOptions(json){try{return json?JSON.parse(json):['','','','']}catch{return ['','','','']}}
function open(row){editing.value=row?.id||null;Object.assign(form,row?{...row,options:parseOptions(row.optionsJson)}:{courseId:courses.value[0]?.id,questionType:'SINGLE_CHOICE',content:'',options:['','','',''],answer:'',analysis:'',difficulty:'EASY',score:5,knowledgeTag:''});visible.value=true}
async function save(){const data={...form,optionsJson:choice.value?JSON.stringify(form.options.filter(Boolean)):null};delete data.options;editing.value?await updateQuestion(editing.value,data):await createQuestion(data);ElMessage.success('保存成功');visible.value=false;load()}
async function remove(id){await ElMessageBox.confirm('确认删除题目？','提示');await deleteQuestion(id);load()}
onMounted(async()=>{courses.value=await getCourses();load()})
</script>
<template><div class="page"><div class="page-header"><h1 class="page-title">题库管理</h1><el-button type="primary" @click="open()">新增题目</el-button></div>
<div class="toolbar"><el-select v-model="query.courseId" clearable placeholder="课程" style="width:180px"><el-option v-for="c in courses" :key="c.id" :label="c.courseName" :value="c.id"/></el-select><el-select v-model="query.questionType" clearable placeholder="题型" style="width:150px"><el-option v-for="t in types" :key="t[0]" :label="t[1]" :value="t[0]"/></el-select><el-select v-model="query.difficulty" clearable placeholder="难度" style="width:130px"><el-option label="简单" value="EASY"/><el-option label="中等" value="MEDIUM"/><el-option label="困难" value="HARD"/></el-select><el-input v-model="query.knowledgeTag" placeholder="知识点" style="width:160px"/><el-button type="primary" @click="load">筛选</el-button></div>
<div class="panel"><el-table :data="rows"><el-table-column prop="content" label="题目" min-width="300" show-overflow-tooltip/><el-table-column prop="questionType" label="题型" width="150"/><el-table-column prop="difficulty" label="难度" width="100"/><el-table-column prop="knowledgeTag" label="知识点" width="140"/><el-table-column prop="score" label="分值" width="80"/><el-table-column label="操作" width="140"><template #default="{row}"><el-button link @click="open(row)">编辑</el-button><el-button link type="danger" @click="remove(row.id)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.size" :total="total" layout="total,prev,pager,next" @current-change="load"/></div>
<el-dialog v-model="visible" :title="editing?'编辑题目':'新增题目'" width="680"><el-form label-width="90"><el-form-item label="课程"><el-select v-model="form.courseId"><el-option v-for="c in courses" :key="c.id" :label="c.courseName" :value="c.id"/></el-select></el-form-item><el-form-item label="题型"><el-select v-model="form.questionType"><el-option v-for="t in types" :key="t[0]" :label="t[1]" :value="t[0]"/></el-select></el-form-item><el-form-item label="题干"><el-input v-model="form.content" type="textarea" :rows="3"/></el-form-item><el-form-item v-if="choice" label="选项"><div class="option-list"><el-input v-for="(_,i) in form.options" :key="i" v-model="form.options[i]"><template #prepend>{{String.fromCharCode(65+i)}}</template></el-input></div></el-form-item><el-form-item label="答案"><el-input v-model="form.answer" :placeholder="form.questionType==='MULTIPLE_CHOICE'?'如 A,B,C':'请输入标准答案'"/></el-form-item><el-form-item label="解析"><el-input v-model="form.analysis" type="textarea"/></el-form-item><el-form-item label="难度"><el-radio-group v-model="form.difficulty"><el-radio-button value="EASY">简单</el-radio-button><el-radio-button value="MEDIUM">中等</el-radio-button><el-radio-button value="HARD">困难</el-radio-button></el-radio-group></el-form-item><el-form-item label="分值"><el-input-number v-model="form.score" :min="1"/></el-form-item><el-form-item label="知识点"><el-input v-model="form.knowledgeTag"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
</div></template>
<style scoped>.option-list{display:grid;gap:8px;width:100%}</style>
