import request from '../utils/request'

export const getCivilModules = () => request.get('/civil-service/modules')
export const getCivilArchiveFilters = () => request.get('/civil-service/archive/filters')
export const getCivilArchiveCatalog = () => request.get('/civil-service/archive/catalog')
export const getCivilPracticeQuestions = params => request.get('/civil-service/practice/questions', { params })
export const startCivilDrill = data => request.post('/civil-service/practice/drill/start', data)
export const getCivilRandomQuestion = params => request.get('/civil-service/practice/random', { params })
export const submitCivilDrillAnswer = data => request.post('/civil-service/practice/drill/answer', data)
export const getCivilTestPaper = params => request.get('/civil-service/test/paper', { params })
export const submitCivilPractice = data => request.post('/civil-service/practice/submit', data)
export const getCivilWrongQuestions = params => request.get('/civil-service/wrong-questions', { params })
export const markCivilWrongMastered = id => request.put(`/civil-service/wrong-questions/${id}/mastered`)
export const deleteCivilWrongQuestion = id => request.delete(`/civil-service/wrong-questions/${id}`)
export const getCivilOverview = () => request.get('/civil-service/analysis/overview')
export const getCivilModuleAnalysis = () => request.get('/civil-service/analysis/modules')
export const getCivilPracticeTrend = () => request.get('/civil-service/analysis/trend')
export const getCivilRecommendations = () => request.get('/civil-service/recommendations')
